import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
const units = {
  year  : 24 * 60 * 60 * 1000 * 365,
  month : 24 * 60 * 60 * 1000 * 365/12,
  day   : 24 * 60 * 60 * 1000,
  hour  : 60 * 60 * 1000,
  minute: 60 * 1000,
  second: 1000
}

const rtf = new Intl.RelativeTimeFormat("en", {
  localeMatcher: "best fit", // other values: "lookup"
  numeric: "always", // other values: "auto"
  style: "long", // other values: "short" or "narrow"
});
const getRelativeTime = (d1, d2 = new Date()) => {
  let elapsed = d1 - d2

  // "Math.abs" accounts for both "past" & "future" scenarios
  for (let u in units) 
    if (Math.abs(elapsed) > units[u] || u == 'second') 
      return rtf.format(Math.round(elapsed/units[u]), u)
}

export default function Home() {
  const [data,setData] = useState()

  useEffect( ()=> {
    fetch("https://newsapi.org/v2/top-headlines?country=us&apiKey=7a1e2a4bb7d641a49383eca2dfc126ae")
      .then((res) => res.json())
      .then((responseJson) => {
        setData(responseJson.articles)
      })
    console.log(data)
  },[])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="container-md text-lg my-5">
          <h1>Berita Terbaru</h1>
          {!data ? "Loading" : 
          data.map((article) => {
            return <div className="card my-3">
              <div class="row g-0">
              <div class="col-md-4">
                <img src={article.urlToImage} class="img-fluid rounded-start" alt={article.description}/>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <h5 class="card-title">{article.title}</h5>
                  <p class="card-text">{article.content}</p>
                  <p class="card-text"><small class="text-body-secondary">Published {getRelativeTime(new Date(article.publishedAt))}</small></p>
                  <a href={article.url}>View in {article.source.name}</a>
                </div>
              </div>
            </div>
          </div>
          })
          }
       
        </div>
      </main>
    </>
  )
}
